//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub mod prelude;

// pub mod auto_code_examples;
// pub mod casbin_rule;
// pub mod config;
// pub mod exa_customers;
// pub mod exa_file_chunks;
// pub mod exa_file_upload_and_downloads;
// pub mod exa_files;
// pub mod jwt_blacklists;
pub mod posts;
// pub mod seaql_migrations;
// pub mod sys_apis;
// pub mod sys_authorities;
// pub mod sys_authority_btns;
// pub mod sys_authority_menus;
// pub mod sys_auto_code_histories;
// pub mod sys_base_menu_btns;
// pub mod sys_base_menu_parameters;
// pub mod sys_base_menus;
// pub mod sys_data_authority_id;
// pub mod sys_dictionaries;
// pub mod sys_dictionary_details;
// pub mod sys_operation_records;
// pub mod sys_user_authority;
// pub mod sys_users;
