//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "sys_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub uuid: Option<String>,
    pub username: Option<String>,
    pub password: Option<String>,
    pub nick_name: Option<String>,
    pub side_mode: Option<String>,
    pub header_img: Option<String>,
    pub base_color: Option<String>,
    pub active_color: Option<String>,
    pub authority_id: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
